### ISSUE TITLE
DomDocument->loadHtml & some html elements causes subscriptions options to fail to add

### ISSUE THREAD

**Issue by Sental** [mollie/magento2-subscriptions#17]
When using the DomDocument method loadHtml() if you have a html elements like <svg> it produces a warning which means the observer fails to add the subscription options to the product page.

Issue identified in `mollie/magento2-subscriptions/Observer/ViewBlockAbstractToHtmlAfter/ChangeAddToCartText.php` on lines 56 & 70 in version 1.3.1.

**Comment by Frank-Magmodules** [comment]
Hi @Sental ,

We are happy to share that we've just released the new [1.4.0](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.4.0) version where we have fixed this issue.  
Thank you for opening this issue and for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
