### ISSUE TITLE
Mollie\Subscriptions\Observer\CustomerLogin\PreventDuplicateSubscriptionProductsInCart relies on observer execution order

### ISSUE THREAD

**Issue by Sental** [mollie/magento2-subscriptions#25]
**Describe the bug**
The cart for a customer is only available on the customer_login event after the observer \Magento\Checkout\Observer\LoadCustomerQuoteObserver. Observers do not have an execution order so they can be fired in a different order. When Mollie\Subscriptions\Observer\CustomerLogin\PreventDuplicateSubscriptionProductsInCart is fired before the Magento observer the customer has no cart so a \Magento\Framework\Exception\NoSuchEntityException is thrown.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.6.0

**To Reproduce**
After you have purchased a subscription while logged in.
1. Add a subscription product to your basket
2. Log into your account
3. You may see a no such entity with customerId  = ... exception

**Expected behavior**
On log in if a duplicate subscription product is in the cart it should be removed.

**Actual behavior**
A clear and concise description of what actually happens.
A no such entity with customerId message is generated and the duplicate subscription product stays in the cart.

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @Sental ,

We are happy to share that we've just released the new [1.6.1](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.6.1) version where we have fixed this issue. Thank you for opening this issue and for your patience. We are closing this issue now but please feel free to reopen the issue if you need any help on this.
