### ISSUE TITLE
Self-test, Check for latest versions and Debug Log are met with a never ending loading screen.

### ISSUE THREAD

**Issue by RutgerHHS** [mollie/magento2-subscriptions#27]
**Describe the bug**
Self-test, Check for latest versions and Debug Log are met with a never ending loading screen.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 1.6.0

**To Reproduce**
1. Install and enable [Mollie Payments](https://github.com/mollie/magento2/).
2. Install and enable [Mollie Subscriptions](https://github.com/mollie/magento2-subscriptions/).
3. Go to your Magento® admin portal and sign in.
4. Go to ‘Stores’ > ‘Configuration’ > ‘Mollie’ > ‘Subscriptions’.
6. Click on 'Run Self-test' / 'Check for latest versions' / 'Check last 100 debug log records' / 'Check last 100 error log records'.

All are met with a never ending loading screen.

**Expected behavior**
A screen showing me any information/output.

**Actual behavior**
![image](https://user-images.githubusercontent.com/42769406/203989489-c986ea68-0df8-40e2-b5ff-9c9121ea3330.png)
![image](https://user-images.githubusercontent.com/42769406/203989574-d9694414-daf6-43b1-b1c5-b7ecba60a3ad.png)
![image](https://user-images.githubusercontent.com/42769406/203989619-565a33ef-1918-4e72-839c-179b31cb1dac.png)
![image](https://user-images.githubusercontent.com/42769406/203991228-92b32821-47ff-4ce9-a08a-1db4a4670582.png)

**Additional context**
Running 'mollie:subscriptions:selftest' gives the following output:
![image](https://user-images.githubusercontent.com/42769406/203990717-19dc8baf-fde9-4cc5-9cff-cce0bcffb2b8.png)

**Comment by Frank-Magmodules** [comment]
Hi @RutgerHHS ,

We are happy to share that we've just released the new [1.6.1](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.6.1) version where we have fixed this issue. Thank you for opening this issue and for your patience. We are closing this issue now but please feel free to reopen the issue if you need any help on this.
