### ISSUE TITLE
No records of a purchased Virtual subscription Product

### ISSUE THREAD

**Issue by RutgerHHS** [mollie/magento2-subscriptions#30]
**Describe the bug**
No records of a purchased Virtual subscription Product.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 1.6.1

**To Reproduce**

*Create a Virtual subscription Product*:
1. Go to your Magento admin portal and sign in.
2. Go to 'Catalog' > 'Products' and create a new Virtual Product. 
3. Fill in the essential details, such as product name, SKUs, and price.
4. Enable 'is this a subscription product' and configure a subscription.
5. When complete, click on the Save menu and select 'Save & Close'.

*Order the Virtual subscription Product*:
1. Go to your Magento storefront and sign in as a customer.
2. Navigate to the previously created Virtual subscription Product. 
3. Add the product to your cart, then pay and complete the order. 

*View active subscriptions in storefront*:
1. After completing the order, go to 'My Account' > 'My Subscriptions'. 

**Expected behavior**
A record showing me any information about the purchased subscription. 

**Actual behavior**
No records.

**Additional context**
- I fetched the latest payment status.
- I used iDeal with the Payments API.

Calling to 'https://api.mollie.com/v2/subscriptions' also results in no records.

**Comment by Frank-Magmodules** [comment]
Hi @RutgerHHS ,

We are happy to share that we've just released the new [1.7.0](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.7.0) version where we have fixed this issue. Thank you for opening this request and for the detailed steps to reproduce.

We are closing this issue now but please feel free to reopen the issue if you need any help on this.
