### ISSUE TITLE
Display a static message when a customer has not purchased any subscription products yet.

### ISSUE THREAD

**Issue by RutgerHHS** [mollie/magento2-subscriptions#31]
# Describe the new feature
Display a static message when a customer has not purchased any subscription products yet.

## Describe the solution to be implemented

**Backend changes**
None.

**Frontend changes**
![image](https://user-images.githubusercontent.com/42769406/205324843-694525c1-0dcd-4a92-bf19-204cd85c3e82.png)

Code used to create the message above:
```
<div class="message info empty"><span><?= $block->escapeHtml(__('You have not purchased any subscription products yet.')) ?></span></div>
```

**Comment by Frank-Magmodules** [comment]
Hi @RutgerHHS ,

We are happy to share that we've just released the new [1.7.0](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.7.0) version where we implemented this!  
Thank you for opening this request.

We are closing this issue now but please feel free to reopen the issue if you need any help on this.
