### ISSUE TITLE
paid subscription not seen in mollie subscriptions page in magento2

### ISSUE THREAD

**Issue by breakerh** [mollie/magento2-subscriptions#4]
**Describe the bug**
A paid subscription is not seen in the mollie subscriptions page in magento2. It's shipped, completed etc.

**Used versions**
- *Magento Version number(eg 2.3.5)*: Magento 2.3.5
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*:  v1.0.0

**To Reproduce**
1. place order with subscription
2. Pay order
3. Ship/complete order

**Expected behavior**
In the mollie subscriptions page you should also see the placed order.

**Actual behavior**
The placed order isn't added to the list.

**Screenshots**
Not needed i think?

**Comment by Frank-Magmodules** [comment]
HI @breakerh ,

Thank you for opening this issue, can you please share your environment details through our [contact form](https://www.magmodules.eu/support-form.html) so we can take a look with you so we can debug this issue?

  
Thanks!

**Comment by breakerh** [comment]
Sorry for the late reply. Will do right away!

**Comment by breakerh** [comment]
Could it maybe be because of the use of Order API? instead of the Payment API.

**Comment by breakerh** [comment]
Had awesome (and fast) help.. Weird thing is, we enabled test mode, disabled it and re-run setup:upgrade etc..
And everything works...

(do have another problem, but responded that to you guys)
