### ISSUE TITLE
[BUG] Subscription product does not show up after updating Mollie Subscription module to v.1.9.0 for existing customers

### ISSUE THREAD

**Issue by CreamDevelopment** [mollie/magento2-subscriptions#40]
**Describe the bug**
We can not order a subscription product for existing customers after updating to Mollie Subscription module v.1.9.0. Also, the existing subscriptions are also not visible anymore in the existing customers account (see screenshot).
However this issue is not occurring for new customers. They can order without any issue.

The following error shows up after ordering in the magento 2 checkout (see screenshot as well).
`[2023-03-13T08:28:42+0000] Error executing API call (404: Not Found): No customer exists with token cst_ffjntq2pLA.. Field: customerId. Documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment`

**Used versions**
- *Magento v.:* 2.4.3-p1
- *Open source v.:* 2.10.12.1
- *Mollie v.:* v2.20.0
- *Mollie Subscription module v.:* v1.9.0

**Expected behavior**
Existing and new curstomers are able to order a subscription product and view them in their account. The following screenshot is the My Account > My Subscription page showing the subscription product (for new customers).

![Expected behavior](https://user-images.githubusercontent.com/59445950/224656521-3e337890-627a-43d1-b64d-6d771aeb7438.png)

**Actual behavior**
The following error occurs after ordering a subscription product in the checkout.

![Screenshot 2023-03-13 at 09 58 51 (3)](https://user-images.githubusercontent.com/59445950/224655414-a66242d6-2e1b-4d3c-8a91-a53f6c548ea4.png)

The following screenshot shows the My Account > My Subscription page (for an existing customers) without any subscriptions.

![Actual behavior](https://user-images.githubusercontent.com/59445950/224656679-5c417800-5ef8-4491-ab85-9d0b999338f5.png)

**Comment by Frank-Magmodules** [comment]
HI @CreamDevelopment ,

Thanks for raising this issue! We haven't been able to replicate it directly. Is it possible that there has been a switch between different API keys or a change between test/live mode?

**Comment by Frank-Magmodules** [comment]
Hello, @CreamDevelopment. Can you please provide an update regarding this matter? Is it still ongoing, or can we consider closing this issue for the time being?

**Comment by Frank-Magmodules** [comment]
We are closing this issue temporarily due to inactivity, but please feel free to reopen it if necessary by mentioning @CreamDevelopment.
