### ISSUE TITLE
All reminder mails on the same date are sent to the same customer

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2-subscriptions#47]
https://github.com/mollie/magento2-subscriptions/blob/aee34ca692f744bcdea231f1d38c96aba3c6e700/Service/Email/SubscriptionToProductEmailVariables.php#L55C1-L57

Caching the customer api response is not a good idea.

The above mentioned line will ensure, that the first customer fetched by the api will receive all reminder emails of all other customers on the same date.

I don't think that this is what you want.

**Comment by Frank-Magmodules** [comment]
Hi @ThomasNegeli , thank you for opening this issue and your patience. We have resolved the issue in our latest release [v1.10.3](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.10.3). I'm closing this issue for now, but feel free to reopen it if you encounter any further problems.
