### ISSUE TITLE
[BUG] No invoice after subscription order is placed

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2-subscriptions#52]
When the Mollie subscription system calls the webhook to place the subscriptoin order in the webshop, the order is placed correctly and visible in the Magento backend.
We have configured Mollie payment module to create the invoice after payment authorization was successfull, but when the order is created during a subscription run, no invoice is created https://github.com/mollie/magento2-subscriptions/blob/main/Controller/Api/Webhook.php#L193

So we have a payment, but we do not have an automatic invoice created. Why don't you use the same logik as in the payment module? https://github.com/mollie/magento2/blob/2d5295974b0fa684e5be2354bb6e3c9f8b62445b/Model/Client/Orders/Processors/SuccessfulPayment.php#L125-L128

**Comment by Frank-Magmodules** [comment]
Hello, @ThomasNegeli!

We appreciate you bringing up this matter. We have received your email containing the necessary details as well, and we will respond to you promptly. Thank you!

**Comment by Frank-Magmodules** [comment]
Thanks for your confirmation @ThomasNegeli , closing this issue.
