### ISSUE TITLE
No customer e-mails after subscription run

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2-subscriptions#53]
The webhook call during subscription run does not send any customer emails, even if the order is placed correctly https://github.com/mollie/magento2-subscriptions/blob/main/Controller/Api/Webhook.php#L173-L196

**Comment by Frank-Magmodules** [comment]
Hey there, @ThomasNegeli! I wanted to double-check if you've come across the option in the configuration section of the Subscription plugin. Could you please confirm if you've noticed it?

![](https://github.com/mollie/magento2-subscriptions/assets/24823946/cb299322-ffff-4321-b4b5-d15351b1be70)

**Comment by ThomasNegeli** [comment]
hi @Frank-Magmodules, the setting is configured with a NO value. This is the default.
You are checking the wrong setting in your code: https://github.com/mollie/magento2-subscriptions/blob/7f6f9b886204b704a06c452b1f38aa112c84f8de/Config.php#L359
This is the problem.

**Comment by Frank-Magmodules** [comment]
Hello @ThomasNegeli, I wanted to let you know that we have been in contact with the Mollie support team regarding this issue. 

However, I wanted to ensure that you are aware that we have resolved the problem you reported in our latest release, version [1.11.0](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.11.0). I will now close this issue, but please feel free to reopen the ticket if needed. 

Thank you once again for bringing this to our attention.
