### ISSUE TITLE
Quantity of subscription product is not respected

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2-subscriptions#54]
https://github.com/mollie/magento2-subscriptions/blob/main/Controller/Api/Webhook.php#L234
Products are added to the cart by their default quantity.
The Mollie documentation is talking about subscription metadata. You are storing the SKU there, but no quantity is used.

**Comment by Frank-Magmodules** [comment]
Hello @ThomasNegeli, I wanted to let you know that we have been in contact with the Mollie support team regarding this issue. 

However, I wanted to ensure that you are aware that we have resolved the problem you reported in our latest release, version [1.11.0](https://github.com/mollie/magento2-subscriptions/releases/tag/v1.11.0). I will now close this issue, but please feel free to reopen the ticket if needed. 

Thank you once again for bringing this to our attention.
