### ISSUE TITLE
No error handling on subscription order submission

### ISSUE THREAD

**Issue by ThomasNegeli** [mollie/magento2-subscriptions#62]
At https://github.com/mollie/magento2-subscriptions/blob/main/Controller/Api/Webhook.php#L223 the cart is submitted and an order is created in Magento.

In our installation we encountered an internal DB deadlock because of a timeout. 
This gave a status 500 error as a result, which Magento logged in var/report. The Mollie backend shows this error 500 on the transaction level.

The result is a payment on Mollie side, but no order creation on Magento side.
This is not the only error that can occur when doing the webhook call.
When an error occurs the request should be retried after some time and afterwards the merchant needs to be informed. No payment should happen.

**Comment by Frank-Magmodules** [comment]
Hello, @ThomasNegeli ! Even though encountering a `status 500` is unexpected, I will discuss the process to handle such situations and ensure the merchant is promptly notified indeed. Have a good weekend ahead for now.

**Comment by Frank-Magmodules** [comment]
Hi There @ThomasNegeli ,

Thanks for opening this issue. In our [latest release](https://github.com/mollie/magento2-subscriptions/), we have addressed this issue. Whenever something goes wrong while creating the recurring order, an email will be sent. Enabling and disabling can be done in the backend under `Stores -> Configuration -> Mollie -> Subscriptions -> Debug. `

There you can also find settings for the contact and email template if required. I will be closing this issue, but please don't hesitate to reopen it if necessary.
