### ISSUE TITLE
[FEATURE]  Virtual & download product Support

### ISSUE THREAD

**Issue by beendeluxe** [mollie/magento2-subscriptions#68]
We are using Magento 2.4.5-p4 and tested the Mollie subscription integration. Its working well for phsysical products. Its simple but effective. 

But... we are facing an error when things go beyond physical products. When for example selling a digital product or a downloadable (digital) product that does not require any shipping method, the extension throws an exception error;
main.CRITICAL: Error: Call to a member function setQuote() on null in /vendor/mollie/magento2-subscriptions/Service/Mollie/GetShippingCostForOrderItem.php:100

That means that the extension requires any shipping method to go ahead. 

Is this already a known bug? We would be happy if this module could also handle digital products. 

Thanks.

**Comment by Frank-Magmodules** [comment]
Hello @beendeluxe, we appreciate you submitting your feature request. We have added it to our feature request list and will update you as soon as we have more information regarding its potential release.

**Comment by beendeluxe** [comment]
The merge works like a charm. Thanks for this quick fix.
