### ISSUE TITLE
Add package on Packagist

### ISSUE THREAD

**Issue by erwinromkes** [mollie/magento2-subscriptions#7]
**Describe the bug**
Composer package is not availeble so a composer install is not working.

**To Reproduce**
1. Run 'composer require mollie/magento2-subscriptions'

**Expected behavior**
That the mollie/magento2-subscriptions package is installed.

**Actual behavior**
The following error:
'Could not find a matching version of package mollie/magento2-subscriptions. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).'

**Additional context**
Looks like the package is removed on Packagist

**Comment by Frank-Magmodules** [comment]
HI @erwinromkes ,

Thanks for your message, finally, we are happy to share that the package is now available on Packagist;  
[https://packagist.org/packages/mollie/magento2-subscriptions](https://packagist.org/packages/mollie/magento2-subscriptions)

We are closing this issue now but please feel free to re-open this issue or create a new one whenever you need any help.
